services:

  app:
    container_name: app
    image: app:latest
    build: ./
    environment:
      - spring.datasource.url=jdbc:mariadb://mariadb:3306/cloudservice
    ports:
      - '8080:8080'
    depends_on:
      - mariadb
    restart: on-failure

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    environment:
      - MARIADB_DATABASE=cloudservice
      - MARIADB_ROOT_PASSWORD=password
    ports:
      - '3306:3306'